### ISSUE TITLE
Please add something descriptive to the github 'about' like 'chess engine' or chess uci engine' (not a real issue)

### ISSUE THREAD

**Issue by rwbc** [ppipelin/radiance_archived#3]
This enables search hits when doing regular update checks for chess engines from users. Thanks for considering :)

e.g. https://github.com/search?o=desc&q=chess+engine&s=updated&type=Repositories
(will never give any hits for Radiance)

Guenther (RWBC)
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM/edit?gid=175552346#gid=175552346

**Comment by SzotsGabor** [comment]
And add some id so that we can distinguish versions.

**Comment by ppipelin** [comment]
There was `chess` in topics but I added more keywords and a description. I will update the license to be GPL3 as well.

What do you mean by ID @SzotsGabor?  There are already version numbers.

**Comment by rwbc** [comment]
Thanks it can be found now with github search (topics alone won't help strangely but the plain text does)

With the ID Gabor means the uci ID. So far it shows neither its real name /version /author for all uci infos before start.

from cmd
(it should be **id name Radiance 3.1**, next line, **id author 'your name'**)
```
uci
id name chessengine

uciok
isready
readyok
position startpos
go depth 12
info failedHighCnt 2 alpha -32001 beta 21365
info depth 1 nodes 22 nps 22000 hash 1 hashfull 0 hashused 0 time 0 multipv 1 score cp 59 pv d2d4
info failedHighCnt 0 alpha -19 beta 59
info depth 2 nodes 79 nps 79000 hash 15 hashfull 0 hashused 0 time 1 multipv 1 score cp 0 pv d2d4 d7d5
info failedHighCnt 1 alpha 0 beta 57
info depth 3 nodes 347 nps 115666 hash 35 hashfull 0 hashused 0 time 3 multipv 1 score cp 43 pv d2d4 e7e5 e2e4 e5d4
info failedHighCnt 0 alpha -19 beta 35
info depth 4 nodes 1253 nps 113909 hash 166 hashfull 0 hashused 0 time 11 multipv 1 score cp 3 pv d2d4 e7e5 e2e4 d7d5 d4e5
info failedHighCnt 1 alpha -4 beta 44
info depth 5 nodes 5366 nps 167687 hash 398 hashfull 0 hashused 0 time 32 multipv 1 score cp 36 pv d2d4 d7d5 e2e4 e7e5 f1b5
info failedHighCnt 0 alpha 4 beta 52
info depth 6 nodes 5769 nps 104890 hash 797 hashfull 0 hashused 0 time 55 multipv 1 score cp 6 pv d2d4 d7d5 e2e4 e7e5 f1b5 c8d7
info failedHighCnt 0 alpha -1 beta 35
info depth 7 nodes 34201 nps 191067 hash 2253 hashfull 0 hashused 0 time 179 multipv 1 score cp 32 pv d2d4 d7d5 e2e4 e7e5 c1d2 f8e7 f1b5
info failedHighCnt 0 alpha 2 beta 46
info depth 8 nodes 15026 nps 62870 hash 2814 hashfull 0 hashused 0 time 239 multipv 1 score cp 8 pv d2d4 d7d5 e2e4 e7e5 c1e3 f8d6 f1e2 c8e6
info failedHighCnt 1 alpha -2 beta 52
info depth 9 nodes 451168 nps 161073 hash 25737 hashfull 0 hashused 663 time 2801 multipv 1 score cp 40 pv e2e4 d7d5 d2d4 e7e5 d4e5 d5d4 f1b5 c8d7 b5d3
info failedHighCnt 0 alpha 6 beta 58
info depth 10 nodes 127535 nps 38460 hash 30381 hashfull 0 hashused 1027 time 3316 multipv 1 score cp 9 pv e2e4 d7d5 d2d4 g8f6 b1c3 e7e5 c1g5 f8b4 f1b5 c8d7
info failedHighCnt 0 alpha 0 beta 40
info depth 11 nodes 263877 nps 61026 hash 38679 hashfull 0 hashused 1634 time 4324 multipv 1 score cp 32 pv e2e4 d7d5 d2d4 g8f6 e4e5 f6e4 f1d3 c8f5 c1g5 h7h6 d3b5

```

**Comment by rwbc** [comment]
And from your output it seems you do an unusual node count, because we can see some weird fluctuations and even going down sometimes with higher depths (should include all visited total nodes from previous searches), this also leads to weird nps fluctuations.

**Comment by ppipelin** [comment]
Updated in https://github.com/ppipelin/radiance/releases/tag/3.1.1
