### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by AlexBrunetti** [ppipelin/radiance_archived#5]
???

**Comment by ppipelin** [comment]
???

**Comment by SzotsGabor** [comment]
Alex is probably wondering where 3.4.1a can be found. I myself have also received a notification about its existence but the link does not work.

**Comment by AlexBrunetti** [comment]
Correct, three notifications between 2 and 3 pm.

**Comment by ppipelin** [comment]
OK, these were pre release as tests for github actions, not sure if pre-release notifications can be supressed.
